SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE `super_agent_chat_dialogue`;
TRUNCATE TABLE `super_agent_chat_exchange`;
TRUNCATE TABLE `super_agent_chat_memory_summary`;
TRUNCATE TABLE `super_agent_chat_exchange_trace_stage`;
TRUNCATE TABLE `GRAPH_THREAD`;
TRUNCATE TABLE `GRAPH_CHECKPOINT`;
TRUNCATE TABLE `super_agent_document`;
TRUNCATE TABLE `super_agent_document_strategy_plan`;
TRUNCATE TABLE `super_agent_document_strategy_step`;
TRUNCATE TABLE `super_agent_document_task`;
TRUNCATE TABLE `super_agent_document_task_log`;
TRUNCATE TABLE `super_agent_document_parse_artifact`;
TRUNCATE TABLE `super_agent_document_block`;
TRUNCATE TABLE `super_agent_document_table`;
TRUNCATE TABLE `super_agent_document_table_column`;
TRUNCATE TABLE `super_agent_document_table_row`;
TRUNCATE TABLE `super_agent_document_table_cell`;
TRUNCATE TABLE `super_agent_document_structure_node`;
TRUNCATE TABLE `super_agent_document_parent_block`;
TRUNCATE TABLE `super_agent_document_chunk`;
TRUNCATE TABLE `super_agent_kg_entity`;
TRUNCATE TABLE `super_agent_kg_relation`;
TRUNCATE TABLE `super_agent_kg_evidence`;
TRUNCATE TABLE `super_agent_kg_community`;
TRUNCATE TABLE `super_agent_raptor_node`;
TRUNCATE TABLE `super_agent_knowledge_scope_node`;
TRUNCATE TABLE `super_agent_knowledge_topic_node`;
TRUNCATE TABLE `super_agent_document_profile`;
TRUNCATE TABLE `super_agent_topic_document_relation`;
TRUNCATE TABLE `super_agent_knowledge_route_trace`;
TRUNCATE TABLE `super_agent_chat_retrieval_result`;
TRUNCATE TABLE `super_agent_chat_channel_execution`;
TRUNCATE TABLE `super_agent_chat_stage_benchmark`;

SET FOREIGN_KEY_CHECKS = 1;